apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user
data:
  MONGO: "true"
  REDIS_URL: {{ .Values.configMap.REDIS_URL }}
  MONGO_URL: {{ .Values.configMap.MONGO_URL }}
