apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: backend
    component: user
  ports:
  - protocol: TCP
    port: 8080 # servie port
    targetPort: 8080 # container port