apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: backend
    component: payment
  ports:
  - protocol: TCP
    port: 8080 # servie port
    targetPort: 8080 # container port